In [1]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df.groupby("性別")[['國文', '英文', '數學', '地理', '歷史']].agg('mean')

           國文         英文         數學         地理         歷史
性別
女   69.285714  69.190476  70.761905  70.714286  65.904762
男   70.482759  63.551724  63.655172  64.241379  68.344828

In [2]:
scores_df

    國文   英文   數學  地理   歷史   姓名 性別
1   78   51   46  76   55  劉彥宏  男
2   61   43   50  72   71  曾彥廷  男
3   55   61   76  49   45  吳子睿  男
4   72   72   44  52   61  蕭志明  男
5   43   70   68  61   85  王文傑  男
6   83   44   79  85   91  朱冠霖  男
7   65   46   58  40   75  謝欣蓉  女
8   72   70   99  60   92  羅淑芬  女
9   42   60  100  49   44  許美慧  女
10  47  100   73  54   78  廖志豪  男
11  90   46   85  90   58  葉柏翰  男
12  97   52  100  52  100  呂承恩  男
13  68  100   71  64   48  蘇雅婷  女
14  66   93   70  52   70  高浩宇  男
15  51   77   53  63   92  王婉茹  女
16  65   64   56  42   65  莊承翰  男
17  80   43   56  65   66  黃裕傑  男
18  81   47   47  78   77  王冠廷  男
19  94   72   43  90   42  呂婉慧  女
20  67   53   56  43   80  莊子謙  男
21  61   66   50  74   79  蘇彥宏  男
22  55   42   54  66   48  李柏融  男
23  99   44   46  58   52  曾明軒  男
24  63   89   52  70   46  呂佳瑩  女
25  40   81   52  88   57  洪怡君  女
26  81   92   90  93   74  洪柏宏  男
27  67   60   58  93   55  江雅琪  女
28  85   72   57  89   53  郭怡萱  女
29  64   74   68  85   90  簡婉慧  女
30  60   63   82  61   54  楊靜宜  女
31  80   60   80  68   79  曾靜儀  女
32  91   79   55  66   98  蕭怡伶  女
33  42   43   99  55   42  洪裕豪  男
34  75   76   46  58   74  簡建宏  男
35  97   90   42  49   68  劉浩然  男
36  96   47   46  88   51  蕭浩宇  男
37  83   50   53  52   76  呂怡靜  女
38  67   91   89  87   95  邱宗翰  男
39  95   42   93  85   50  彭美慧  女
40  67   57   62  73   65  劉靜芬  女
41  81   47   86  79   42  許淑芬  女
42  59   52   40  56   41  邱裕豪  男
43  77   92   80  48  100  吳雅萍  女
44  56   99   87  67   97  施子軒  男
45  98   58   41  54   76  莊柏融  男
46  51   40   59  62   50  鍾浩銘  男
47  62   87   91  71   66  周美玲  女
48  48   75   93  91   60  劉婉婷  女
49  66   72   94  63   52  曾明哲  男
50  56   92   57  62   81  詹柏翰  男

In [3]:
scores_df['總分'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)

scores_df['總分階級'] = pd.cut(
    scores_df['總分'],
    bins=[0, 250, 350, 500],
    labels=['低分區', '一般區', '高分區']
)
scores_df
scores_df.groupby(['性別', '總分階級'])['總分'].agg(['count', 'mean', 'min', 'max'])

         count   mean  min  max
性別 總分階級
女  一般區      11  320.0  284  341
   高分區      10  374.3  351  397
男  低分區       1  248.0  248  248
   一般區      20  310.5  262  348
   高分區       8  390.0  351  430